package com.novare.atm.util;

public enum MenuContext {

	WELCOME, SIGNUP, LOGIN,

	MAIN,

	USER, UPDATE, CHANGE_PASSWORD,

	TRANSACTION, VIEW_BALANCE, WITHDRAW_MONEY, TRANSFER_MONEY, DEPOSIT_MONEY,

	LOGOUT;
}
