package com.novare.atm.util;

public enum MenuContext {

	WELCOME, SIGNUP, LOGIN,

	MAIN,

	USER, UPDATE_USER, CHANGE_PASSWORD,DELETE_USER,

	ACCOUNT, VIEW_BALANCE, WITHDRAW_MONEY, TRANSFER_MONEY, DEPOSIT_MONEY,

	LOGOUT;
}
